apiVersion: v1
kind: Service
metadata:
  name: {{ include "analytics-manager.fullname" . }}
  labels:
    {{- include "analytics-manager.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "analytics-manager.selectorLabels" . | nindent 4 }}
