 
"""
Connected DAG Dummy Job Manager (200 Items)
=================================================

This dummy server generates *deterministic, layered DAG-style scheduling-lineage data*
for testing the Lineage Manager ingestion pipeline.

----------------------------------------------------------------------
1. What this server does
----------------------------------------------------------------------

When Lineage Manager calls:

    GET /api/v1/jobs/scheduling-lineage?scheduling_type=...

this server returns up to 200 synthetic lineage objects, each representing:

    - A Job (SELF-TYPE or REQUEST-TYPE)
    - Exactly one downstream output table
    - One or more upstream inputs (tables or S3 paths)

The output is deterministic and fully reproducible.

The dataset simulates *layered ETL pipelines* like this:

    Layer 1: 50 jobs, each reading from one source table
    Layer 2: 25 jobs, each reading from a Layer 1 output
    Layer 3: 25 jobs, reading from (source table + Layer 1 output)
    Layer 4: 25 jobs, reading from Layer 2 job output + S3
    Layer 5: 25 jobs, reading from multiple layers + S3
    Extra 50 jobs: copies of simple jobs to reach exactly 200 total entries

Finally:
    - 100 jobs are labeled as "SELF-TYPE"
    - 100 jobs are labeled as "REQUEST-TYPE"
and they are paginated through offset/limit.

----------------------------------------------------------------------
2. DAG Structure Generated
----------------------------------------------------------------------

SOURCE TABLES (50)
    demo.analytics.SRC_TABLE_001
    ...
    demo.analytics.SRC_TABLE_050

LAYER 1: 50 jobs (each reads 1 source table → writes L1_OUT_xxx)
LAYER 2: 25 jobs (reads L1 outputs → writes L2_OUT_xxx)
LAYER 3: 25 jobs (reads source + L1 output → writes L3_OUT_xxx)
LAYER 4: 25 jobs (reads L2 output + S3 → writes L4_OUT_xxx)
LAYER 5: 25 jobs (multi-source: source + L1 + L2 + L3 + S3 → writes L5_OUT_xxx)
EXTRA: 50 jobs (simple source-read → EXTRA_OUT_xxx)

Total = 200 connected job nodes.

Each job produces exactly 1 downstream table.

----------------------------------------------------------------------
3. Table Name Format Rule
----------------------------------------------------------------------

**All dataset tables strictly follow the BigQuery-style identifier format:**

    project.dataset.table_name

Examples generated by this dummy server:

    demo.analytics.SRC_TABLE_001
    demo.analytics.L1_OUT_023
    demo.analytics.L4_OUT_010
    demo.analytics.EXTRA_OUT_150

This guarantees compatibility with Lineage Manager DB schema rules and
BigQuery-like parsing logic.

----------------------------------------------------------------------
4. Upstream Format Rules
----------------------------------------------------------------------

Tables:
    {"type": "table", "name": "demo.analytics.SRC_TABLE_001", "trigger": True}

S3 Paths:
    {"type": "s3", "name": "s3://dummy-bucket/layer4/1", "trigger": False}

----------------------------------------------------------------------
5. Downstream Format Rule
----------------------------------------------------------------------

Every job writes exactly 1 table:

    {"type": "table", "name": "demo.analytics.L2_OUT_003"}

----------------------------------------------------------------------
6. Pagination Behavior
----------------------------------------------------------------------

GET /api/v1/jobs/scheduling-lineage/?offset=X&limit=Y

returns:

    {
        "result": [... lineage objects ...],
        "pagination": {
            "offset": X,
            "limit": Y,
            "next_offset": N or null
        }
    }

This mimics the real Job Manager's paging logic.
"""

from fastapi import FastAPI, Query
from typing import Optional
from datetime import datetime, timedelta, timezone
import re

app = FastAPI(
    title="Connected DAG Dummy Job Manager (200 items, strict table naming)",
    docs_url="/docs",
    redoc_url="/redoc",
    openapi_url="/openapi.json",
)


# =====================================================================
# Table Name Validator
# =====================================================================
TABLE_NAME_PATTERN = re.compile(r"^[a-zA-Z0-9_\-]+\.([a-zA-Z0-9_\-]+)\.([a-zA-Z0-9_\-]+)$")


def validate_table_name(name: str) -> str:
    """
    Enforces the rule:
        project.dataset.table

    Valid example:
        demo.analytics.SRC_TABLE_001

    Invalid examples:
        demo/analytics/table
        demo.analytics
        table_only

    Raises ValueError immediately if format is incorrect.
    """
    if not TABLE_NAME_PATTERN.match(name):
        raise ValueError(f"Invalid table name format: '{name}'. "
                         f"Expected: project.dataset.table")
    return name


def is_s3(name: str) -> bool:
    return name.startswith("s3://")


# =====================================================================
# Lineage Object Builder
# =====================================================================
def build_lineage(job, lineage_type):
    """Converts internal job descriptor → scheduling-lineage JSON with strict table name validation."""

    upstreams = []
    for src in job["reads"]:
        if is_s3(src):
            upstreams.append({"type": "s3", "name": src, "trigger": False})
        else:
            validate_table_name(src)
            upstreams.append({"type": "table", "name": src, "trigger": True})

    downstream_table = validate_table_name(job["writes"][0])

    return {
        "type": lineage_type,
        "job_id": job["job_id"],
        "name": job["job_id"],
        "upstreams": upstreams,
        "downstreams": [{"type": "table", "name": downstream_table}],
        "destination_type": "table",
        "schedule": {"cron": "@daily"},
        "meta": {
            "owner": "tester",
            "labels": {"env": "test"},
            "write_mode": "append",
            "run_status": "RUN",
        },
        "create_datetime": "2024-12-01T02:00:00Z",
        "update_datetime": "2024-12-01T03:15:00Z",
        "successful_dag_runs_count": 10,
    }


# =====================================================================
# STEP 1: Source tables (strict naming)
# =====================================================================
SOURCE_TABLE_COUNT = 50
SOURCE_TABLES = [
    validate_table_name(f"demo.analytics.SRC_TABLE_{i:03d}")
    for i in range(1, SOURCE_TABLE_COUNT + 1)
]


# =====================================================================
# STEP 2: Layer 1 Jobs (50 jobs)
# =====================================================================
L1 = []
for i in range(1, 51):
    src_table = SOURCE_TABLES[(i - 1) % SOURCE_TABLE_COUNT]
    out_table = validate_table_name(f"demo.analytics.L1_OUT_{i:03d}")

    L1.append({
        "job_id": f"L1_JOB_{i:03d}",
        "reads": [src_table],
        "writes": [out_table],
    })


# =====================================================================
# STEP 3: Layer 2 Jobs (25 jobs)
# =====================================================================
L2 = []
for i in range(1, 26):
    parent_out = L1[(i - 1) % 50]["writes"][0]
    out_table = validate_table_name(f"demo.analytics.L2_OUT_{i:03d}")

    L2.append({
        "job_id": f"L2_JOB_{i:03d}",
        "reads": [parent_out],
        "writes": [out_table],
    })


# =====================================================================
# STEP 4: Layer 3 Jobs (25 jobs)
# =====================================================================
L3 = []
for i in range(1, 26):
    src_table = SOURCE_TABLES[(i - 1) % 50]
    l1_out = L1[(i - 1) % 50]["writes"][0]
    out_table = validate_table_name(f"demo.analytics.L3_OUT_{i:03d}")

    L3.append({
        "job_id": f"L3_JOB_{i:03d}",
        "reads": [src_table, l1_out],
        "writes": [out_table],
    })


# =====================================================================
# STEP 5: Layer 4 Jobs (25 jobs)
# =====================================================================
L4 = []
for i in range(1, 26):
    l2_out = L2[(i - 1) % 25]["writes"][0]
    s3_path = f"s3://dummy-bucket/layer4/{i}"
    out_table = validate_table_name(f"demo.analytics.L4_OUT_{i:03d}")

    L4.append({
        "job_id": f"L4_JOB_{i:03d}",
        "reads": [l2_out, s3_path],
        "writes": [out_table],
    })


# =====================================================================
# STEP 6: Layer 5 Jobs (25 jobs)
# =====================================================================
L5 = []
for i in range(1, 26):
    reads = [
        SOURCE_TABLES[(i - 1) % 50],
        L1[(i - 1) % 50]["writes"][0],
        L2[(i - 1) % 25]["writes"][0],
        L3[(i - 1) % 25]["writes"][0],
        f"s3://dummy-bucket/multi/{i}",
    ]
    out_table = validate_table_name(f"demo.analytics.L5_OUT_{i:03d}")

    L5.append({
        "job_id": f"L5_JOB_{i:03d}",
        "reads": reads,
        "writes": [out_table],
    })


# =====================================================================
# Combine Jobs → 200 jobs (strict table names)
# =====================================================================
ALL_JOBS = L1 + L2 + L3 + L4 + L5

# Add extra jobs to reach 200, enforcing strict naming
while len(ALL_JOBS) < 200:
    index = len(ALL_JOBS) + 1
    src = SOURCE_TABLES[index % 50]
    out_table = validate_table_name(f"demo.analytics.EXTRA_OUT_{index:03d}")

    ALL_JOBS.append({
        "job_id": f"EXTRA_JOB_{index:03d}",
        "reads": [src],
        "writes": [out_table],
    })


assert len(ALL_JOBS) == 200


# =====================================================================
# Assign types
# =====================================================================
SELF_JOBS = ALL_JOBS[:100]
REQUEST_JOBS = ALL_JOBS[100:200]

SELF_DATA = [build_lineage(job, "SELF-TYPE") for job in SELF_JOBS]
REQ_DATA = [build_lineage(job, "REQUEST-TYPE") for job in REQUEST_JOBS]
ALL_DATA = SELF_DATA + REQ_DATA


# =====================================================================
# API Endpoint
# =====================================================================
@app.get("/api/v1/jobs/scheduling-lineage/")
def get_scheduling_lineage(
    scheduling_type: Optional[str] = Query(default=None),
    offset: int = 0,
    limit: int = 100,
):
    """Paginated deterministic lineage data with strict naming rules."""

    if scheduling_type == "SELF-TYPE":
        filtered = SELF_DATA
    elif scheduling_type == "REQUEST-TYPE":
        filtered = REQ_DATA
    else:
        filtered = ALL_DATA

    total = len(filtered)
    end = offset + limit
    page = filtered[offset:end]
    next_offset = end if end < total else None

    return {
        "status": "success",
        "result": page,
        "pagination": {
            "limit": limit,
            "offset": offset,
            "next_offset": next_offset,
            "total": total,
        },
    }


@app.get("/job/{job_id}/run-history")
def get_job_run_history(job_id: str):
    """Return 30 synthetic run-history items for the given job."""
    base_end = datetime(2025, 12, 3, 1, 0, tzinfo=timezone.utc)
    runs = []
    for idx in range(30):
        end_at = base_end - timedelta(days=idx)
        start_at = end_at + timedelta(hours=-72 + (idx % 6))
        state = ["RUNNING", "SUCCESS", "FAILED", "SUCCESS", "SUCCESS", "FAILED"][idx % 6]
        finish_time = None if state == "RUNNING" else start_at + timedelta(minutes=30 + idx)
        runs.append(
            {
                "job_id": job_id,
                "data_interval_end": end_at.strftime("%Y-%m-%dT%H:%M:%S"),
                "dag_run_id": f"scheduled__{(end_at - timedelta(days=1)).isoformat()}",
                "state": state,
                "start_time": start_at.strftime("%Y-%m-%dT%H:%M:%S"),
                "finish_time": finish_time.strftime("%Y-%m-%dT%H:%M:%S") if finish_time else None,
                "delay_criteria": [],
                "notified": False if state != "RUNNING" else None,
            }
        )
    return runs
from datetime import datetime, timedelta, timezone

@app.get("/job/{job_id}/run-history")
def get_job_run_history(job_id: str):
    """Return 30 synthetic run-history items for the given job."""
    base_end = datetime(2025, 12, 3, 1, 0, tzinfo=timezone.utc)
    runs = []
    for idx in range(30):
        end_at = base_end - timedelta(days=idx)
        start_at = end_at + timedelta(hours=-72 + (idx % 6))  # some variety
        # Alternate states
        state = ["RUNNING", "SUCCESS", "FAILED", "SUCCESS", "SUCCESS", "FAILED"][idx % 6]
        finish_time = None if state == "RUNNING" else start_at + timedelta(minutes=30 + idx)
        runs.append(
            {
                "job_id": job_id,
                "data_interval_end": end_at.strftime("%Y-%m-%dT%H:%M:%S"),
                "dag_run_id": f"scheduled__{(end_at - timedelta(days=1)).isoformat()}",
                "state": state,
                "start_time": start_at.strftime("%Y-%m-%dT%H:%M:%S"),
                "finish_time": finish_time.strftime("%Y-%m-%dT%H:%M:%S") if finish_time else None,
                "delay_criteria": [],
                "notified": False if state != "RUNNING" else None,
            }
        )
    return runs
