 
"""
Connected DAG Dummy Job Manager (200 Items)
=================================================

This dummy server generates *deterministic, layered DAG-style scheduling-lineage data*
for testing the Lineage Manager ingestion pipeline.

----------------------------------------------------------------------
1. What this server does
----------------------------------------------------------------------

When Lineage Manager calls:

    GET /api/v1/jobs/scheduling-lineage?scheduling_type=...

this server returns up to 200 synthetic lineage objects, each representing:

    - A Job (SELF-TYPE or REQUEST-TYPE)
    - Exactly one downstream output table
    - One or more upstream inputs (tables or S3 paths)

The output is deterministic and fully reproducible.

The dataset simulates *layered ETL pipelines* like this:

    Layer 1: 50 jobs, each reading from one source table
    Layer 2: 25 jobs, each reading from a Layer 1 output
    Layer 3: 25 jobs, reading from (source table + Layer 1 output)
    Layer 4: 25 jobs, reading from Layer 2 job output + S3
    Layer 5: 25 jobs, reading from multiple layers + S3
    Extra 50 jobs: copies of simple jobs to reach exactly 200 total entries

Finally:
    - 100 jobs are labeled as "SELF-TYPE"
    - 100 jobs are labeled as "REQUEST-TYPE"
and they are paginated through offset/limit.

----------------------------------------------------------------------
2. DAG Structure Generated
----------------------------------------------------------------------

SOURCE TABLES (50)
    demo.analytics.SRC_TABLE_001
    ...
    demo.analytics.SRC_TABLE_050

LAYER 1: 50 jobs (each reads 1 source table → writes L1_OUT_xxx)
LAYER 2: 25 jobs (reads L1 outputs → writes L2_OUT_xxx)
LAYER 3: 25 jobs (reads source + L1 output → writes L3_OUT_xxx)
LAYER 4: 25 jobs (reads L2 output + S3 → writes L4_OUT_xxx)
LAYER 5: 25 jobs (multi-source: source + L1 + L2 + L3 + S3 → writes L5_OUT_xxx)
EXTRA: 50 jobs (simple source-read → EXTRA_OUT_xxx)

Total = 200 connected job nodes.

Each job produces exactly 1 downstream table.

----------------------------------------------------------------------
3. Table Name Format Rule
----------------------------------------------------------------------

**All dataset tables strictly follow the BigQuery-style identifier format:**

    project.dataset.table_name

Examples generated by this dummy server:

    demo.analytics.SRC_TABLE_001
    demo.analytics.L1_OUT_023
    demo.analytics.L4_OUT_010
    demo.analytics.EXTRA_OUT_150

This guarantees compatibility with Lineage Manager DB schema rules and
BigQuery-like parsing logic.

----------------------------------------------------------------------
4. Upstream Format Rules
----------------------------------------------------------------------

Tables:
    {"type": "table", "name": "demo.analytics.SRC_TABLE_001", "trigger": True}

S3 Paths:
    {"type": "s3", "name": "s3://dummy-bucket/layer4/1", "trigger": False}

----------------------------------------------------------------------
5. Downstream Format Rule
----------------------------------------------------------------------

Every job writes exactly 1 table:

    {"type": "table", "name": "demo.analytics.L2_OUT_003"}

----------------------------------------------------------------------
6. Pagination Behavior
----------------------------------------------------------------------

GET /api/v1/jobs/scheduling-lineage/?offset=X&limit=Y

returns:

    {
        "result": [... lineage objects ...],
        "pagination": {
            "offset": X,
            "limit": Y,
            "next_offset": N or null
        }
    }

This mimics the real Job Manager's paging logic.
"""
from pydantic import BaseModel
from fastapi import FastAPI, Query
from typing import Optional, List
from datetime import datetime, timedelta, timezone
import re



app = FastAPI(
    title="Connected DAG Dummy Job Manager (200 items, strict table naming)",
    docs_url="/docs",
    redoc_url="/redoc",
    openapi_url="/openapi.json",
)


# =====================================================================
# Table Name Validator
# =====================================================================
TABLE_NAME_PATTERN = re.compile(r"^[a-zA-Z0-9_\-]+\.([a-zA-Z0-9_\-]+)\.([a-zA-Z0-9_\-]+)$")


def validate_table_name(name: str) -> str:
    """
    Enforces the rule:
        project.dataset.table

    Valid example:
        demo.analytics.SRC_TABLE_001

    Invalid examples:
        demo/analytics/table
        demo.analytics
        table_only

    Raises ValueError immediately if format is incorrect.
    """
    if not TABLE_NAME_PATTERN.match(name):
        raise ValueError(f"Invalid table name format: '{name}'. "
                         f"Expected: project.dataset.table")
    return name


# 1) Request body models
class JobSelector(BaseModel):
    scheduling_type: str
    job_id: str

class JobSelectorRequest(BaseModel):
    jobs: List[JobSelector]
    
def is_s3(name: str) -> bool:
    return name.startswith("s3://")


# =====================================================================
# Lineage Object Builder
# =====================================================================
def build_lineage(job, lineage_type):
    """Converts internal job descriptor → scheduling-lineage JSON with strict table name validation."""

    upstreams = []
    for src in job["reads"]:
        if is_s3(src):
            upstreams.append({"type": "s3", "name": src, "trigger": False})
        else:
            validate_table_name(src)
            upstreams.append({"type": "table", "name": src, "trigger": True})

    downstream_table = validate_table_name(job["writes"][0])

    return {
        "type": lineage_type,
        "job_id": job["job_id"],
        "name": job["job_id"],
        "upstreams": upstreams,
        "downstreams": [{"type": "table", "name": downstream_table}],
        "destination_type": "table",
        "schedule": {"cron": "@daily"},
        "meta": {
            "owner": "tester",
            "labels": {"env": "test"},
            "write_mode": "append",
            "run_status": "RUN",
        },
        "create_datetime": "2024-12-01T02:00:00Z",
        "update_datetime": "2024-12-01T03:15:00Z",
        "successful_dag_runs_count": 10,
    }


# =====================================================================
# STEP 1: Source tables (strict naming)
# =====================================================================
SOURCE_TABLE_COUNT = 50
SOURCE_TABLES = [
    validate_table_name(f"demo.analytics.SRC_TABLE_{i:03d}")
    for i in range(1, SOURCE_TABLE_COUNT + 1)
]


# =====================================================================
# STEP 2: Layer 1 Jobs (50 jobs)
# =====================================================================
L1 = []
for i in range(1, 51):
    src_table = SOURCE_TABLES[(i - 1) % SOURCE_TABLE_COUNT]
    out_table = validate_table_name(f"demo.analytics.L1_OUT_{i:03d}")

    L1.append({
        "job_id": f"L1_JOB_{i:03d}",
        "reads": [src_table],
        "writes": [out_table],
    })


# =====================================================================
# STEP 3: Layer 2 Jobs (25 jobs)
# =====================================================================
L2 = []
for i in range(1, 26):
    parent_out = L1[(i - 1) % 50]["writes"][0]
    out_table = validate_table_name(f"demo.analytics.L2_OUT_{i:03d}")

    L2.append({
        "job_id": f"L2_JOB_{i:03d}",
        "reads": [parent_out],
        "writes": [out_table],
    })


# =====================================================================
# STEP 4: Layer 3 Jobs (25 jobs)
# =====================================================================
L3 = []
for i in range(1, 26):
    src_table = SOURCE_TABLES[(i - 1) % 50]
    l1_out = L1[(i - 1) % 50]["writes"][0]
    out_table = validate_table_name(f"demo.analytics.L3_OUT_{i:03d}")

    L3.append({
        "job_id": f"L3_JOB_{i:03d}",
        "reads": [src_table, l1_out],
        "writes": [out_table],
    })


# =====================================================================
# STEP 5: Layer 4 Jobs (25 jobs)
# =====================================================================
L4 = []
for i in range(1, 26):
    l2_out = L2[(i - 1) % 25]["writes"][0]
    s3_path = f"s3://dummy-bucket/layer4/{i}"
    out_table = validate_table_name(f"demo.analytics.L4_OUT_{i:03d}")

    L4.append({
        "job_id": f"L4_JOB_{i:03d}",
        "reads": [l2_out, s3_path],
        "writes": [out_table],
    })


# =====================================================================
# STEP 6: Layer 5 Jobs (25 jobs)
# =====================================================================
L5 = []
for i in range(1, 26):
    reads = [
        SOURCE_TABLES[(i - 1) % 50],
        L1[(i - 1) % 50]["writes"][0],
        L2[(i - 1) % 25]["writes"][0],
        L3[(i - 1) % 25]["writes"][0],
        f"s3://dummy-bucket/multi/{i}",
    ]
    out_table = validate_table_name(f"demo.analytics.L5_OUT_{i:03d}")

    L5.append({
        "job_id": f"L5_JOB_{i:03d}",
        "reads": reads,
        "writes": [out_table],
    })


# =====================================================================
# Combine Jobs → 200 jobs (strict table names)
# =====================================================================
ALL_JOBS = L1 + L2 + L3 + L4 + L5

# Add extra jobs to reach 200, enforcing strict naming
while len(ALL_JOBS) < 200:
    index = len(ALL_JOBS) + 1
    src = SOURCE_TABLES[index % 50]
    out_table = validate_table_name(f"demo.analytics.EXTRA_OUT_{index:03d}")

    ALL_JOBS.append({
        "job_id": f"EXTRA_JOB_{index:03d}",
        "reads": [src],
        "writes": [out_table],
    })


assert len(ALL_JOBS) == 200


# =====================================================================
# Assign types
# =====================================================================
SELF_JOBS = ALL_JOBS[:100]
REQUEST_JOBS = ALL_JOBS[100:200]

SELF_DATA = [build_lineage(job, "SELF-TYPE") for job in SELF_JOBS]
REQ_DATA = [build_lineage(job, "REQUEST-TYPE") for job in REQUEST_JOBS]
ALL_DATA = SELF_DATA + REQ_DATA


# =====================================================================
# API Endpoint
# =====================================================================
@app.get("/api/v1/jobs/scheduling-lineage/")
def get_scheduling_lineage(
    scheduling_type: Optional[str] = Query(default=None),
    offset: int = 0,
    limit: int = 100,
):
    """Paginated deterministic lineage data with strict naming rules."""

    if scheduling_type == "SELF-TYPE":
        filtered = SELF_DATA
    elif scheduling_type == "REQUEST-TYPE":
        filtered = REQ_DATA
    else:
        filtered = ALL_DATA

    total = len(filtered)
    end = offset + limit
    page = filtered[offset:end]
    next_offset = end if end < total else None

    return {
        "status": "success",
        "result": page,
        "pagination": {
            "limit": limit,
            "offset": offset,
            "next_offset": next_offset,
            "total": total,
        },
    }


@app.get("/job/{job_id}/run-history")
def get_job_run_history(job_id: str):
    """Return 30 synthetic run-history items for the given job."""
    base_end = datetime(2025, 12, 3, 1, 0, tzinfo=timezone.utc)
    runs = []
    for idx in range(30):
        end_at = base_end - timedelta(days=idx)
        start_at = end_at + timedelta(hours=-72 + (idx % 6))
        state = ["RUNNING", "SUCCESS", "FAILED", "SUCCESS", "SUCCESS", "FAILED"][idx % 6]
        finish_time = None if state == "RUNNING" else start_at + timedelta(minutes=30 + idx)
        runs.append(
            {
                "job_id": job_id,
                "data_interval_end": end_at.strftime("%Y-%m-%dT%H:%M:%S"),
                "dag_run_id": f"scheduled__{(end_at - timedelta(days=1)).isoformat()}",
                "state": state,
                "start_time": start_at.strftime("%Y-%m-%dT%H:%M:%S"),
                "finish_time": finish_time.strftime("%Y-%m-%dT%H:%M:%S") if finish_time else None,
                "delay_criteria": [],
                "notified": False if state != "RUNNING" else None,
            }
        )
    return runs
from datetime import datetime, timedelta, timezone

@app.get("/job/{job_id}/run-history")
def get_job_run_history(job_id: str):
    """Return 30 synthetic run-history items for the given job."""
    base_end = datetime(2025, 12, 3, 1, 0, tzinfo=timezone.utc)
    runs = []
    for idx in range(30):
        end_at = base_end - timedelta(days=idx)
        start_at = end_at + timedelta(hours=-72 + (idx % 6))  # some variety
        # Alternate states
        state = ["RUNNING", "SUCCESS", "FAILED", "SUCCESS", "SUCCESS", "FAILED"][idx % 6]
        finish_time = None if state == "RUNNING" else start_at + timedelta(minutes=30 + idx)
        runs.append(
            {
                "job_id": job_id,
                "data_interval_end": end_at.strftime("%Y-%m-%dT%H:%M:%S"),
                "dag_run_id": f"scheduled__{(end_at - timedelta(days=1)).isoformat()}",
                "state": state,
                "start_time": start_at.strftime("%Y-%m-%dT%H:%M:%S"),
                "finish_time": finish_time.strftime("%Y-%m-%dT%H:%M:%S") if finish_time else None,
                "delay_criteria": [],
                "notified": False if state != "RUNNING" else None,
            }
        )
    return runs


@app.post("/api/v1/jobs/scheduling-lineage/by_ids")
def get_scheduling_lineage_by_ids(payload: JobSelectorRequest):
    """
    테스트용 API:
    - Body로 { jobs: [ { scheduling_type, job_id }, ... ] } 를 받는다.
    - 각 job에 대해 GET /api/v1/jobs/scheduling-lineage/ 와 동일한 형태의
      scheduling-lineage 객체를 생성해서 반환한다.
    - upstreams / downstreams 는 각각 5개씩 더미로 생성.
    """

    results = []

    for idx, item in enumerate(payload.jobs, start=1):
        # 5개 upstream (모두 table 타입, trigger=True)
        upstreams = [
            {
                "type": "table",
                "name": f"demo.analytics.BYIDS_UP_{idx}_{i:03d}",
                "trigger": True,
            }
            for i in range(1, 6)
        ]

        # 5개 downstream (모두 table 타입)
        downstreams = [
            {
                "type": "table",
                "name": f"demo.analytics.BYIDS_DOWN_{idx}_{i:03d}",
            }
            for i in range(1, 6)
        ]

        lineage = {
            "type": item.scheduling_type,          # 요청 그대로
            "job_id": item.job_id,                 # 요청 그대로
            "name": item.job_id,
            "upstreams": upstreams,
            "downstreams": downstreams,
            "destination_type": "table",
            "schedule": {"cron": "@daily"},
            "meta": {
                "owner": "tester",
                "labels": {"env": "test", "source": "by_ids"},
                "write_mode": "append",
                "run_status": "RUN",
            },
            "create_datetime": "2024-12-01T02:00:00Z",
            "update_datetime": "2024-12-01T03:15:00Z",
            "successful_dag_runs_count": 10,
        }

        results.append(lineage)

    total = len(results)
    offset = 0
    limit = total
    next_offset = None

    return {
        "status": "success",
        "result": results,
        "pagination": {
            "limit": limit,
            "offset": offset,
            "next_offset": next_offset,
            "total": total,
        },
    }


@app.post("/api/v1/jobs/scheduling-lineage/progressive_test")
def get_progressive_expansion_test_data(payload: JobSelectorRequest):
    """
    Progressive Expansion 테스트용 API:
    - 41개의 계층적 job 데이터 생성
    - Level 0: 20 jobs (각 Level 1 job의 upstream)
    - Level 1: 10 jobs (CENTER_JOB의 upstream)
    - Level 2: 1 CENTER_JOB
    - Level 3: 10 jobs (CENTER_JOB의 downstream)
    
    요청된 job_id에 따라 적절한 upstream/downstream 반환
    """
    
    results = []
    requested_job_ids = {item.job_id for item in payload.jobs}
    
    # Level 0 jobs (20 jobs) - 각각 1개의 input, 1개의 output
    for i in range(1, 21):
        job_id = f"LEVEL0_JOB_{i:03d}"
        if job_id in requested_job_ids:
            results.append({
                "type": "SELF-TYPE",
                "job_id": job_id,
                "name": job_id,
                "upstreams": [
                    {"type": "table", "name": f"test.level0.input_{i:03d}", "trigger": True}
                ],
                "downstreams": [
                    {"type": "table", "name": f"test.level0.output_{i:03d}"}
                ],
                "destination_type": "table",
                "schedule": {"cron": "@daily"},
                "meta": {
                    "owner": "test_user",
                    "labels": {"level": "0", "test": "progressive_expansion"},
                    "write_mode": "append",
                    "run_status": "RUN",
                },
                "create_datetime": "2024-12-01T02:00:00Z",
                "update_datetime": "2024-12-01T03:15:00Z",
                "successful_dag_runs_count": 10,
            })
    
    # Level 1 jobs (10 jobs) - 각각 2개의 Level 0 output을 읽음
    for i in range(1, 11):
        job_id = f"LEVEL1_JOB_{i:03d}"
        if job_id in requested_job_ids:
            upstream_idx1 = (i - 1) * 2 + 1
            upstream_idx2 = (i - 1) * 2 + 2
            
            results.append({
                "type": "SELF-TYPE",
                "job_id": job_id,
                "name": job_id,
                "upstreams": [
                    {"type": "table", "name": f"test.level0.output_{upstream_idx1:03d}", "trigger": True},
                    {"type": "table", "name": f"test.level0.output_{upstream_idx2:03d}", "trigger": True},
                ],
                "downstreams": [
                    {"type": "table", "name": f"test.level1.output_{i:03d}"}
                ],
                "destination_type": "table",
                "schedule": {"cron": "@daily"},
                "meta": {
                    "owner": "test_user",
                    "labels": {"level": "1", "test": "progressive_expansion"},
                    "write_mode": "append",
                    "run_status": "RUN",
                },
                "create_datetime": "2024-12-01T02:00:00Z",
                "update_datetime": "2024-12-01T03:15:00Z",
                "successful_dag_runs_count": 10,
            })
    
    # CENTER_JOB - 10개의 Level 1 output을 읽음
    if "CENTER_JOB" in requested_job_ids:
        upstreams = [
            {"type": "table", "name": f"test.level1.output_{i:03d}", "trigger": True}
            for i in range(1, 11)
        ]
        
        results.append({
            "type": "SELF-TYPE",
            "job_id": "CENTER_JOB",
            "name": "CENTER_JOB",
            "upstreams": upstreams,
            "downstreams": [
                {"type": "table", "name": "test.center.main_output"}
            ],
            "destination_type": "table",
            "schedule": {"cron": "@daily"},
            "meta": {
                "owner": "test_user",
                "labels": {"level": "2", "test": "progressive_expansion", "center": "true"},
                "write_mode": "append",
                "run_status": "RUN",
            },
            "create_datetime": "2024-12-01T02:00:00Z",
            "update_datetime": "2024-12-01T03:15:00Z",
            "successful_dag_runs_count": 10,
        })
    
    # Level 3 jobs (10 jobs) - CENTER output을 읽음
    for i in range(1, 11):
        job_id = f"LEVEL3_JOB_{i:03d}"
        if job_id in requested_job_ids:
            results.append({
                "type": "SELF-TYPE",
                "job_id": job_id,
                "name": job_id,
                "upstreams": [
                    {"type": "table", "name": "test.center.main_output", "trigger": True}
                ],
                "downstreams": [
                    {"type": "table", "name": f"test.level3.output_{i:03d}"}
                ],
                "destination_type": "table",
                "schedule": {"cron": "@daily"},
                "meta": {
                    "owner": "test_user",
                    "labels": {"level": "3", "test": "progressive_expansion"},
                    "write_mode": "append",
                    "run_status": "RUN",
                },
                "create_datetime": "2024-12-01T02:00:00Z",
                "update_datetime": "2024-12-01T03:15:00Z",
                "successful_dag_runs_count": 10,
            })
    
    total = len(results)
    
    return {
        "status": "success",
        "result": results,
        "pagination": {
            "limit": total,
            "offset": 0,
            "next_offset": None,
            "total": total,
        },
    }

