 
"""
Connected DAG Dummy Job Manager (200 Items)
=================================================

This dummy server generates *deterministic, layered DAG-style scheduling-lineage data*
for testing the Lineage Manager ingestion pipeline.

----------------------------------------------------------------------
1. What this server does
----------------------------------------------------------------------

When Lineage Manager calls:

    GET /api/v1/jobs/scheduling-lineage?scheduling_type=...

this server returns up to 200 synthetic lineage objects, each representing:

    - A Job (SELF-TYPE or REQUEST-TYPE)
    - Exactly one downstream output table
    - One or more upstream inputs (tables or S3 paths)

The output is deterministic and fully reproducible.

The dataset simulates *layered ETL pipelines* like this:

    Layer 1: 50 jobs, each reading from one source table
    Layer 2: 25 jobs, each reading from a Layer 1 output
    Layer 3: 25 jobs, reading from (source table + Layer 1 output)
    Layer 4: 25 jobs, reading from Layer 2 job output + S3
    Layer 5: 25 jobs, reading from multiple layers + S3
    Extra 50 jobs: copies of simple jobs to reach exactly 200 total entries

Finally:
    - 100 jobs are labeled as "SELF-TYPE"
    - 100 jobs are labeled as "REQUEST-TYPE"
and they are paginated through offset/limit.

----------------------------------------------------------------------
2. DAG Structure Generated
----------------------------------------------------------------------

SOURCE TABLES (50)
    demo.analytics.SRC_TABLE_001
    ...
    demo.analytics.SRC_TABLE_050

LAYER 1: 50 jobs (each reads 1 source table → writes L1_OUT_xxx)
LAYER 2: 25 jobs (reads L1 outputs → writes L2_OUT_xxx)
LAYER 3: 25 jobs (reads source + L1 output → writes L3_OUT_xxx)
LAYER 4: 25 jobs (reads L2 output + S3 → writes L4_OUT_xxx)
LAYER 5: 25 jobs (multi-source: source + L1 + L2 + L3 + S3 → writes L5_OUT_xxx)
EXTRA: 50 jobs (simple source-read → EXTRA_OUT_xxx)

Total = 200 connected job nodes.

Each job produces exactly 1 downstream table.

----------------------------------------------------------------------
3. Table Name Format Rule
----------------------------------------------------------------------

**All dataset tables strictly follow the BigQuery-style identifier format:**

    project.dataset.table_name

Examples generated by this dummy server:

    demo.analytics.SRC_TABLE_001
    demo.analytics.L1_OUT_023
    demo.analytics.L4_OUT_010
    demo.analytics.EXTRA_OUT_150

This guarantees compatibility with Lineage Manager DB schema rules and
BigQuery-like parsing logic.

----------------------------------------------------------------------
4. Upstream Format Rules
----------------------------------------------------------------------

Tables:
    {"type": "table", "name": "demo.analytics.SRC_TABLE_001", "trigger": True}

S3 Paths:
    {"type": "s3", "name": "s3://dummy-bucket/layer4/1", "trigger": False}

----------------------------------------------------------------------
5. Downstream Format Rule
----------------------------------------------------------------------

Every job writes exactly 1 table:

    {"type": "table", "name": "demo.analytics.L2_OUT_003"}

----------------------------------------------------------------------
6. Pagination Behavior
----------------------------------------------------------------------

GET /api/v1/jobs/scheduling-lineage/?offset=X&limit=Y

returns:

    {
        "result": [... lineage objects ...],
        "pagination": {
            "offset": X,
            "limit": Y,
            "next_offset": N or null
        }
    }

This mimics the real Job Manager's paging logic.
"""
from pydantic import BaseModel
from fastapi import FastAPI, Query
from typing import Optional, List
from datetime import datetime, timedelta, timezone
import re
import random



app = FastAPI(
    title="Connected DAG Dummy Job Manager (200 items, strict table naming)",
    docs_url="/docs",
    redoc_url="/redoc",
    openapi_url="/openapi.json",
)


# =====================================================================
# Table Name Validator
# =====================================================================
TABLE_NAME_PATTERN = re.compile(r"^[a-zA-Z0-9_\-]+\.([a-zA-Z0-9_\-]+)\.([a-zA-Z0-9_\-]+)$")


def validate_table_name(name: str) -> str:
    """
    Enforces the rule:
        project.dataset.table

    Valid example:
        demo.analytics.SRC_TABLE_001

    Invalid examples:
        demo/analytics/table
        demo.analytics
        table_only

    Raises ValueError immediately if format is incorrect.
    """
    if not TABLE_NAME_PATTERN.match(name):
        raise ValueError(f"Invalid table name format: '{name}'. "
                         f"Expected: project.dataset.table")
    return name


# 1) Request body models
class JobSelector(BaseModel):
    type: str
    job_id: str

class JobSelectorRequest(BaseModel):
    jobs: List[JobSelector]
    
def is_s3(name: str) -> bool:
    return name.startswith("s3://")

def get_storage(name: str) -> str:
    if name.startswith("s3://"): return "s3"
    if name.startswith("gs://"): return "gcs"
    return "bigquery"

def format_dependency(name, is_upstream=True):
    storage = get_storage(name)
    dep = {
        "type": "table",
        "name": name,
        "storage": storage
    }
    if is_upstream:
        dep["dependency_type"] = "SOFT" if storage != "bigquery" else "HARD"
    else:
        dep["write_mode"] = "OVERWRITE" if storage != "bigquery" else "APPEND"
    return dep

def format_lineage_object(job_id, lineage_type, upstreams, downstreams, owner="tester", labels=None):
    if labels is None:
        # Generate some random variety for labels
        service_names = ["\"tv\" sales", "data_pipeline", "user_analytics", "revenue_tracking", "customer_360"]
        priorities = [1, 2, 3, 4]
        emails = ["123@aa.com", "dev-team@company.io", "ops@monitoring.net"]
        envs = ["test", "prod", "staging", "dev"]
        
        labels = {
            "env": random.choice(envs),
            "service_name": random.choice(service_names),
            "priority": random.choice(priorities),
            "email": random.choice(emails),
            "is_active": random.choice([True, False]),
            "version": f"v1.{random.randint(0, 9)}",
        }
        
        # Occasionally add extra noise
        if random.random() > 0.5:
            labels["tag"] = random.choice(["critical", "internal", "legacy", "external"])
    
    return {
        "job_id": job_id,
        "type": lineage_type.replace("-TYPE", ""),
        "name": job_id,
        "status": "RUNNING",
        "upstreams": upstreams,
        "downstreams": downstreams,
        "schedule": {
            "cron_expression": "@daily",
            "start_date": "2025-10-03",
            "end_date": "2025-12-01"
        },
        "governance": {
            "include_pii": True
        },
        "metadata": {
            "owner": owner,
            "labels": labels,
            "lifecycle_status": "DEPLOYED"
        }
    }


# =====================================================================
# Lineage Object Builder
# =====================================================================
def build_lineage(job, lineage_type):
    """Converts internal job descriptor → scheduling-lineage JSON with strict table name validation."""

    upstreams = []
    for src in job["reads"]:
        if get_storage(src) == "bigquery": validate_table_name(src)
        upstreams.append(format_dependency(src, is_upstream=True))

    downstreams = []
    for out in job["writes"]:
        if get_storage(out) == "bigquery": validate_table_name(out)
        downstreams.append(format_dependency(out, is_upstream=False))

    return format_lineage_object(job["job_id"], lineage_type, upstreams, downstreams)


# =====================================================================
# STEP 1: Source tables (strict naming)
# =====================================================================
SOURCE_TABLE_COUNT = 50
SOURCE_TABLES = [
    validate_table_name(f"demo.analytics.SRC_TABLE_{i:03d}")
    for i in range(1, SOURCE_TABLE_COUNT + 1)
]


# =====================================================================
# STEP 2: Layer 1 Jobs (50 jobs)
# =====================================================================
L1 = []
for i in range(1, 51):
    src_table = SOURCE_TABLES[(i - 1) % SOURCE_TABLE_COUNT]
    out_table = validate_table_name(f"demo.analytics.L1_OUT_{i:03d}")

    L1.append({
        "job_id": f"L1_JOB_{i:03d}",
        "reads": [src_table],
        "writes": [out_table],
    })


# =====================================================================
# STEP 3: Layer 2 Jobs (25 jobs)
# =====================================================================
L2 = []
for i in range(1, 26):
    parent_out = L1[(i - 1) % 50]["writes"][0]
    out_table = validate_table_name(f"demo.analytics.L2_OUT_{i:03d}")

    L2.append({
        "job_id": f"L2_JOB_{i:03d}",
        "reads": [parent_out],
        "writes": [out_table],
    })


# =====================================================================
# STEP 4: Layer 3 Jobs (25 jobs)
# =====================================================================
L3 = []
for i in range(1, 26):
    src_table = SOURCE_TABLES[(i - 1) % 50]
    l1_out = L1[(i - 1) % 50]["writes"][0]
    out_table = validate_table_name(f"demo.analytics.L3_OUT_{i:03d}")

    L3.append({
        "job_id": f"L3_JOB_{i:03d}",
        "reads": [src_table, l1_out],
        "writes": [out_table],
    })


# =====================================================================
# STEP 5: Layer 4 Jobs (25 jobs)
# =====================================================================
L4 = []
for i in range(1, 26):
    l2_out = L2[(i - 1) % 25]["writes"][0]
    s3_path = f"s3://dummy-bucket/layer4/{i}"
    out_table = validate_table_name(f"demo.analytics.L4_OUT_{i:03d}")

    L4.append({
        "job_id": f"L4_JOB_{i:03d}",
        "reads": [l2_out, s3_path],
        "writes": [out_table],
    })


# =====================================================================
# STEP 6: Layer 5 Jobs (25 jobs)
# =====================================================================
L5 = []
for i in range(1, 26):
    reads = [
        SOURCE_TABLES[(i - 1) % 50],
        L1[(i - 1) % 50]["writes"][0],
        L2[(i - 1) % 25]["writes"][0],
        L3[(i - 1) % 25]["writes"][0],
        f"s3://dummy-bucket/multi/{i}",
    ]
    out_table = validate_table_name(f"demo.analytics.L5_OUT_{i:03d}")

    L5.append({
        "job_id": f"L5_JOB_{i:03d}",
        "reads": reads,
        "writes": [out_table],
    })


# =====================================================================
# Combine Jobs → 200 jobs (strict table names)
# =====================================================================
ALL_JOBS = L1 + L2 + L3 + L4 + L5

# Add extra jobs to reach 200, enforcing strict naming
while len(ALL_JOBS) < 200:
    index = len(ALL_JOBS) + 1
    src = SOURCE_TABLES[index % 50]
    out_table = validate_table_name(f"demo.analytics.EXTRA_OUT_{index:03d}")

    ALL_JOBS.append({
        "job_id": f"EXTRA_JOB_{index:03d}",
        "reads": [src],
        "writes": [out_table],
    })


assert len(ALL_JOBS) == 200


# =====================================================================
# Assign types
# =====================================================================
SELF_JOBS = ALL_JOBS[:100]
REQUEST_JOBS = ALL_JOBS[100:200]

SELF_DATA = [build_lineage(job, "SELF-TYPE") for job in SELF_JOBS]
REQ_DATA = [build_lineage(job, "REQUEST-TYPE") for job in REQUEST_JOBS]
ALL_DATA = SELF_DATA + REQ_DATA


# =====================================================================
# API Endpoint
# =====================================================================
@app.get("/api/v1/jobs/scheduling-lineage/")
def get_scheduling_lineage(
    scheduling_type: Optional[str] = Query(default=None),
    offset: int = 0,
    limit: int = 100,
):
    """Paginated deterministic lineage data with strict naming rules."""

    if scheduling_type == "SELF-TYPE":
        filtered = SELF_DATA
    elif scheduling_type == "REQUEST-TYPE":
        filtered = REQ_DATA
    else:
        filtered = ALL_DATA

    total = len(filtered)
    end = offset + limit
    page = filtered[offset:end]
    next_offset = end if end < total else None

    return {
        "status": "success",
        "result": page,
        "pagination": {
            "limit": limit,
            "offset": offset,
            "next_offset": next_offset,
            "total": total,
        },
    }


@app.get("/job/{job_id}/run-history")
def get_job_run_history(job_id: str):
    """Return 30 synthetic run-history items for the given job."""
    base_end = datetime(2025, 12, 3, 1, 0, tzinfo=timezone.utc)
    runs = []
    for idx in range(30):
        end_at = base_end - timedelta(days=idx)
        start_at = end_at + timedelta(hours=-72 + (idx % 6))
        state = ["RUNNING", "SUCCESS", "FAILED", "SUCCESS", "SUCCESS", "FAILED"][idx % 6]
        finish_time = None if state == "RUNNING" else start_at + timedelta(minutes=30 + idx)
        runs.append(
            {
                "job_id": job_id,
                "data_interval_end": end_at.strftime("%Y-%m-%dT%H:%M:%S"),
                "dag_run_id": f"scheduled__{(end_at - timedelta(days=1)).isoformat()}",
                "state": state,
                "start_time": start_at.strftime("%Y-%m-%dT%H:%M:%S"),
                "finish_time": finish_time.strftime("%Y-%m-%dT%H:%M:%S") if finish_time else None,
                "delay_criteria": [],
                "notified": False if state != "RUNNING" else None,
            }
        )
    return runs
from datetime import datetime, timedelta, timezone

@app.get("/job/{job_id}/run-history")
def get_job_run_history(job_id: str):
    """Return 30 synthetic run-history items for the given job."""
    base_end = datetime(2025, 12, 3, 1, 0, tzinfo=timezone.utc)
    runs = []
    for idx in range(30):
        end_at = base_end - timedelta(days=idx)
        start_at = end_at + timedelta(hours=-72 + (idx % 6))  # some variety
        # Alternate states
        state = ["RUNNING", "SUCCESS", "FAILED", "SUCCESS", "SUCCESS", "FAILED"][idx % 6]
        finish_time = None if state == "RUNNING" else start_at + timedelta(minutes=30 + idx)
        runs.append(
            {
                "job_id": job_id,
                "data_interval_end": end_at.strftime("%Y-%m-%dT%H:%M:%S"),
                "dag_run_id": f"scheduled__{(end_at - timedelta(days=1)).isoformat()}",
                "state": state,
                "start_time": start_at.strftime("%Y-%m-%dT%H:%M:%S"),
                "finish_time": finish_time.strftime("%Y-%m-%dT%H:%M:%S") if finish_time else None,
                "delay_criteria": [],
                "notified": False if state != "RUNNING" else None,
            }
        )
    return runs


@app.post("/api/v1/jobs/scheduling-lineage/by_ids")
def get_scheduling_lineage_by_ids(payload: JobSelectorRequest):
    """
    테스트용 API:
    - Body로 { jobs: [ { scheduling_type, job_id }, ... ] } 를 받는다.
    - 만약 job_id가 LEVEL... 이나 CENTER_JOB 이면 progressive_test 데이터 반환.
    - 그 외에는 더미 데이터 반환.
    """
    # 1. 퀘리 대상 중 progressive test용 ID가 있는지 확인
    test_ids = {"CENTER_JOB"} | {f"LEVEL{lvl}_JOB_{i:03d}" for lvl in range(4) for i in range(1, 21)}
    deep_test_ids = {"DEEP_CENTER_JOB"} | {f"UP_L{lvl}_JOB_{i:03d}" for lvl in range(1, 6) for i in range(1, 11)} | {f"DOWN_L{lvl}_JOB_{i:03d}" for lvl in range(1, 6) for i in range(1, 11)}
    massive_test_ids = {"MASSIVE_CENTER_JOB"} | {f"MA_UP_L{lvl}_JOB_{i:03d}" for lvl in range(1, 11) for i in range(1, 11)} | {f"MA_DOWN_L{lvl}_JOB_{i:03d}" for lvl in range(1, 11) for i in range(1, 11)}
    
    # 2. 요청된 ID들 중 테스트 ID가 하나라도 있으면 적절한 로직으로 처리
    requested_ids = {j.job_id for j in payload.jobs}
    if requested_ids & test_ids:
        return get_progressive_expansion_test_data(payload)
    if requested_ids & deep_test_ids:
        return get_deep_lineage_test_data(payload)
    if requested_ids & massive_test_ids:
        return get_massive_lineage_test_data(payload)

    results = []
    for idx, item in enumerate(payload.jobs, start=1):
        upstreams = [
            format_dependency(f"demo.analytics.BYIDS_UP_{idx}_{i:03d}", is_upstream=True)
            for i in range(1, 6)
        ]
        downstreams = [
            format_dependency(f"demo.analytics.BYIDS_DOWN_{idx}_{i:03d}", is_upstream=False)
            for i in range(1, 6)
        ]

        results.append(format_lineage_object(
            item.job_id, item.type, upstreams, downstreams, 
            labels={"env": "test", "source": "by_ids"}
        ))

    return {
        "status": "success",
        "result": results,
        "pagination": {"limit": len(results), "offset": 0, "next_offset": None, "total": len(results)},
    }


@app.post("/api/v1/jobs/scheduling-lineage/progressive_test")
def get_progressive_expansion_test_data(payload: JobSelectorRequest):
    """
    Progressive Expansion 테스트용 API:
    - 41개의 계층적 job 데이터 생성
    - Level 0: 20 jobs (각 Level 1 job의 upstream)
    - Level 1: 10 jobs (CENTER_JOB의 upstream)
    - Level 2: 1 CENTER_JOB
    - Level 3: 10 jobs (CENTER_JOB의 downstream)
    
    요청된 job_id에 따라 적절한 upstream/downstream 반환
    """
    
    results = []
    requested_job_ids = {item.job_id for item in payload.jobs}
    
    # Level 0 jobs (20 jobs) - 각각 1개의 input, 1개의 output
    for i in range(1, 21):
        job_id = f"LEVEL0_JOB_{i:03d}"
        if job_id in requested_job_ids:
            results.append(format_lineage_object(
                job_id, "SELF-TYPE",
                [format_dependency(f"test.level0.input_{i:03d}", is_upstream=True)],
                [format_dependency(f"test.level0.output_{i:03d}", is_upstream=False)],
                owner="test_user",
                labels={"level": "0", "test": "progressive_expansion"}
            ))
    
    # Level 1 jobs (10 jobs) - 각각 2개의 Level 0 output을 읽음
    for i in range(1, 11):
        job_id = f"LEVEL1_JOB_{i:03d}"
        if job_id in requested_job_ids:
            upstream_idx1 = (i - 1) * 2 + 1
            upstream_idx2 = (i - 1) * 2 + 2
            
            results.append(format_lineage_object(
                job_id, "SELF-TYPE",
                [
                    format_dependency(f"test.level0.output_{upstream_idx1:03d}", is_upstream=True),
                    format_dependency(f"test.level0.output_{upstream_idx2:03d}", is_upstream=True),
                ],
                [format_dependency(f"test.level1.output_{i:03d}", is_upstream=False)],
                owner="test_user",
                labels={"level": "1", "test": "progressive_expansion"}
            ))
    
    # CENTER_JOB - 10개의 Level 1 output을 읽음
    if "CENTER_JOB" in requested_job_ids:
        upstreams = [
            format_dependency(f"test.level1.output_{i:03d}", is_upstream=True)
            for i in range(1, 11)
        ]
        
        results.append(format_lineage_object(
            "CENTER_JOB", "SELF-TYPE",
            upstreams,
            [format_dependency("test.center.main_output", is_upstream=False)],
            owner="test_user",
            labels={"level": "2", "test": "progressive_expansion", "center": "true"}
        ))
    
    # Level 3 jobs (10 jobs) - CENTER output을 읽음
    for i in range(1, 11):
        job_id = f"LEVEL3_JOB_{i:03d}"
        if job_id in requested_job_ids:
            results.append(format_lineage_object(
                job_id, "SELF-TYPE",
                [format_dependency("test.center.main_output", is_upstream=True)],
                [format_dependency(f"test.level3.output_{i:03d}", is_upstream=False)],
                owner="test_user",
                labels={"level": "3", "test": "progressive_expansion"}
            ))
    
    total = len(results)
    
    return {
        "status": "success",
        "result": results,
        "pagination": {
            "limit": total,
            "offset": 0,
            "next_offset": None,
            "total": total,
        },
    }


@app.post("/api/v1/jobs/scheduling-lineage/deep_test")
def get_deep_lineage_test_data(payload: JobSelectorRequest):
    """
    5단계 계층 구조 테스트 데이터 생성:
    - Center Job: DEEP_CENTER_JOB
    - Upstream: UP_L1 ~ UP_L5 (각 10개)
    - Downstream: DOWN_L1 ~ DOWN_L5 (각 10개)
    """
    results = []
    requested_job_ids = {item.job_id for item in payload.jobs}
    
    def build_job(job_id, level_name, upstreams, downstreams):
        return format_lineage_object(
            job_id, "SELF-TYPE",
            upstreams,
            downstreams,
            owner="test_user",
            labels={"level": level_name, "test": "deep_lineage"}
        )

    # Center Job
    if "DEEP_CENTER_JOB" in requested_job_ids:
        ups = [format_dependency(f"test.deep.up_l1.out_{i:03d}", is_upstream=True) for i in range(1, 11)]
        downs = [format_dependency(f"test.deep.down_l1.in_{i:03d}", is_upstream=False) for i in range(1, 11)]
        results.append(build_job("DEEP_CENTER_JOB", "center", ups, downs))

    # Upstream Levels 1-5
    for lvl in range(1, 6):
        for i in range(1, 11):
            job_id = f"UP_L{lvl}_JOB_{i:03d}"
            if job_id in requested_job_ids:
                if lvl < 5:
                    # L1-L4 read from next level
                    ups = [format_dependency(f"test.deep.up_l{lvl+1}.out_{j:03d}", is_upstream=True) for j in range(1, 11)]
                else:
                    # L5 is root
                    ups = [format_dependency(f"test.deep.root.in_{i:03d}", is_upstream=True)]
                
                # Output table name matches what the level below it expects
                out_table = f"test.deep.up_l{lvl}.out_{i:03d}"
                results.append(build_job(job_id, f"up_l{lvl}", ups, [format_dependency(out_table, is_upstream=False)]))

    # Downstream Levels 1-5
    for lvl in range(1, 6):
        for i in range(1, 11):
            job_id = f"DOWN_L{lvl}_JOB_{i:03d}"
            if job_id in requested_job_ids:
                if lvl == 1:
                    # L1 reads from center output
                    # Note: Original requirements says "10 up, down stream and then 5 levels further"
                    # We'll make all 10 L1 jobs read the same center output table (or one of them)
                    # To keep it simple, they all read the first center output table
                    ups = [format_dependency(f"test.deep.down_l1.in_{i:03d}", is_upstream=True)]
                else:
                    # L2-L5 read from level above
                    ups = [format_dependency(f"test.deep.down_l{lvl-1}.out_{i:03d}", is_upstream=True)]
                
                out_table = f"test.deep.down_l{lvl}.out_{i:03d}"
                results.append(build_job(job_id, f"down_l{lvl}", ups, [format_dependency(out_table, is_upstream=False)]))

    total = len(results)
    return {
        "status": "success",
        "result": results,
        "pagination": {"limit": total, "offset": 0, "next_offset": None, "total": total},
    }


@app.post("/api/v1/jobs/scheduling-lineage/massive_test")
def get_massive_lineage_test_data(payload: JobSelectorRequest):
    """
    10단계 계층 구조, 4-way branching 테스트 데이터 생성:
    - Center Job: MASSIVE_CENTER_JOB
    - Upstream: MA_UP_L1 ~ MA_UP_L10 (각 10개)
    - Downstream: MA_DOWN_L1 ~ MA_DOWN_L10 (각 10개)
    - 각 노드는 다음 레벨의 4개 노드와 연결됨.
    """
    results = []
    requested_job_ids = {item.job_id for item in payload.jobs}
    
    def build_job(job_id, level_name, upstreams, downstreams):
        return format_lineage_object(
            job_id, "SELF-TYPE",
            upstreams,
            downstreams,
            owner="massive_user",
            labels={"level": level_name, "test": "massive_lineage"}
        )

    # Center Job
    if "MASSIVE_CENTER_JOB" in requested_job_ids:
        # Connects to 4 L1 upstreams and produces 4 L1 downstream inputs
        ups = [format_dependency(f"test.massive.up_l1.out_{i:03d}", is_upstream=True) for i in range(1, 5)]
        downs = [format_dependency(f"test.massive.down_l1.in_{i:03d}", is_upstream=False) for i in range(1, 5)]
        results.append(build_job("MASSIVE_CENTER_JOB", "center", ups, downs))

    # Upstream Levels 1-10
    for lvl in range(1, 11):
        for i in range(1, 11):
            job_id = f"MA_UP_L{lvl}_JOB_{i:03d}"
            if job_id in requested_job_ids:
                # Upstreams: 4 nodes from the NEXT level
                if lvl < 10:
                    # Each node i connects to nodes [i, i+1, i+2, i+3] (modulo 10) in lvl+1
                    up_indices = [( (i-1+j) % 10 ) + 1 for j in range(4)]
                    ups = [format_dependency(f"test.massive.up_l{lvl+1}.out_{idx:03d}", is_upstream=True) for idx in up_indices]
                else:
                    # Level 10 is root level
                    ups = [format_dependency(f"test.massive.root.in_{i:03d}", is_upstream=True)]
                
                # Downstreams: The table this level produces
                out_table = f"test.massive.up_l{lvl}.out_{i:03d}"
                results.append(build_job(job_id, f"up_l{lvl}", ups, [format_dependency(out_table, is_upstream=False)]))

    # Downstream Levels 1-10
    for lvl in range(1, 11):
        for i in range(1, 11):
            job_id = f"MA_DOWN_L{lvl}_JOB_{i:03d}"
            if job_id in requested_job_ids:
                # Upstreams: The table(s) from the PREVIOUS level
                if lvl == 1:
                    # Level 1 reads from center output (4 tables total, let's distribute)
                    # node 1-3 -> center.out_001, 4-6 -> 002, 7-9 -> 003, 10 -> 004
                    center_idx = min((i-1)//3 + 1, 4)
                    ups = [format_dependency(f"test.massive.down_l1.in_{center_idx:03d}", is_upstream=True)]
                else:
                    # Each node i reads from 4 nodes in lvl-1
                    prev_indices = [( (i-1+j) % 10 ) + 1 for j in range(4)]
                    ups = [format_dependency(f"test.massive.down_l{lvl-1}.out_{idx:03d}", is_upstream=True) for idx in prev_indices]
                
                out_table = f"test.massive.down_l{lvl}.out_{i:03d}"
                results.append(build_job(job_id, f"down_l{lvl}", ups, [format_dependency(out_table, is_upstream=False)]))

    total = len(results)
    return {
        "status": "success",
        "result": results,
        "pagination": {"limit": total, "offset": 0, "next_offset": None, "total": total},
    }

