apiVersion: v1
kind: Secret
metadata:
  name: lineage-manager-secret
  namespace: self-scheduling-dev1
type: Opaque
data:
  # Database credentials (base64 encoded)
  DB_NAME: "base64-encoded-database-name"
  DB_USER: "base64-encoded-database-user" # ss_admin
  DB_PASSWORD: "base64-encoded-database-password" # Samsungpw1!
  
  # OIDC credentials (base64 encoded)
  # APP_OIDC_CLIENT_ID: "base64-encoded-client-id"
  # APP_OIDC_CLIENT_SECRET: "base64-encoded-client-secret"
  
  # Note: These values should be base64 encoded
  # To encode: echo -n 'your-value' | base64
