name: admin-console

include:
  - path: ./apps/backend/docker-compose.yml
  - path: ./apps/frontend/docker-compose.yml

networks:
  admin-console-network:
    name: admin-console-network
    driver: bridge

volumes:
  mysql_v2_data:
