services:
  admin-console-app:
    build:
      context: ./container
      dockerfile: deploy/docker/Dockerfile
      args:
        - LINEAGE_MFE_URL=http://localhost:5101/mfe-lineage/remoteEntry.js
        - CATALOG_MFE_URL=http://localhost:5102/mfe-catalog/remoteEntry.js
    container_name: admin-console-app
    ports:
      - "${SHELL_PORT:-5100}:80"
    environment:
      - API_BASE_URL=/admin-console
      - BASE_URL=${BASE_URL:-/admin-console}
      - BACKEND_HOST=http://app-manager:5003/lineage-manager
      - LINEAGE_MFE_URL=http://localhost:5101/mfe-lineage/remoteEntry.js
      - CATALOG_MFE_URL=http://localhost:5102/mfe-catalog/remoteEntry.js
      - ENABLE_MFE_LINEAGE=${ENABLE_MFE_LINEAGE:-true}
      - ENABLE_MFE_CATALOG=${ENABLE_MFE_CATALOG:-true}
      - NODE_ENV=production
    networks:
      - admin-network
      - backend-network

  admin-mfe-lineage:
    build:
      context: ./mfe-lineage
      dockerfile: deploy/docker/Dockerfile
      args:
        - LINEAGE_MFE_URL=http://localhost:5101/mfe-lineage/remoteEntry.js
        - CATALOG_MFE_URL=http://localhost:5102/mfe-catalog/remoteEntry.js
    container_name: admin-mfe-lineage
    ports:
      - "${LINEAGE_PORT:-5101}:80"
    environment:
      - API_BASE_URL=/admin-console
      - BASE_URL=${LINEAGE_BASE_URL:-/mfe-lineage}
      - BACKEND_HOST=http://app-manager:5003/lineage-manager
    networks:
      - admin-network
      - backend-network

  admin-mfe-catalog:
    build:
      context: ./mfe-catalog
      dockerfile: deploy/docker/Dockerfile
      args:
        - LINEAGE_MFE_URL=http://localhost:5101/mfe-lineage/remoteEntry.js
        - CATALOG_MFE_URL=http://localhost:5102/mfe-catalog/remoteEntry.js
    container_name: admin-mfe-catalog
    ports:
      - "${TABLE_DETAIL_PORT:-5102}:80"
    environment:
      - API_BASE_URL=/admin-console
      - BASE_URL=${CATALOG_BASE_URL:-/mfe-catalog}
      - BACKEND_HOST=http://app-manager:5003/lineage-manager
    networks:
      - admin-network
      - backend-network

networks:
  admin-network:
    driver: bridge
  backend-network:
    external: false
    name: backend_backend-network
