"""fix_missing_tables

Revision ID: c19f39155355
Revises: c2ffced35cbf
Create Date: 2026-01-27 08:39:02.010703+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0006_fix_missing_tables'
down_revision: Union[str, None] = '0005_remove_legacy_indices'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema and optionally migrate data."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Removing redundant create_table calls as they are handled in 0003_add_meta_tables
    
    op.alter_column('graph_closure', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('graph_closure', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('graph_edge', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('graph_edge', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('graph_node', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('graph_node', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    
    # 0004 already handled user_id nullable=False, but ensuring status default is removed
    op.alter_column('user_account', 'status',
               existing_type=sa.String(length=20),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Rollback changes made in the upgrade function."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_account', 'status',
               existing_type=sa.String(length=20),
               server_default=sa.text("'ACTIVE'"),
               existing_nullable=True)
    # Skipping redundant drops and reverts already handled by other migrations
    # ### end Alembic commands ###