"""
Connected DAG Dummy Job Manager (Static JSON)
=================================================

This dummy server serves a static dataset of 2000 jobs (generated by data_generator.py)
representing a 5-layer lineage graph with real BigQuery table names.
"""
from pydantic import BaseModel
from fastapi import FastAPI, Query
from typing import Optional, List
import json
import os
from datetime import datetime, timedelta, timezone

app = FastAPI(
    title="Connected DAG Dummy Job Manager (Static JSON)",
    docs_url="/docs",
    redoc_url="/redoc",
    openapi_url="/openapi.json",
)

# Load Static Data on Startup
ALL_DATA = []
try:
    if os.path.exists("dummy_lineage.json"):
        with open("dummy_lineage.json", "r") as f:
            STATIC_DATA = json.load(f)
            ALL_DATA = STATIC_DATA.get("items", [])
            print(f"Loaded {len(ALL_DATA)} jobs from dummy_lineage.json")
    else:
        print("WARNING: dummy_lineage.json not found. Run data_generator.py first.")
except Exception as e:
    print(f"ERROR loading dummy_lineage.json: {e}")


# =====================================================================
# Request body models
# =====================================================================
class JobSelector(BaseModel):
    type: str
    job_id: str

class JobSelectorRequest(BaseModel):
    jobs: List[JobSelector]

# =====================================================================
# API Endpoints
# =====================================================================
@app.get("/api/v1/jobs/scheduling-lineage/")
def get_scheduling_lineage(
    scheduling_type: Optional[str] = Query(default=None),
    offset: int = 0,
    limit: int = 100,
):
    """Paginated static lineage data from file."""
    
    # Simple filtering based on internal 'type' field which matches scheduling_type
    filtered = ALL_DATA
    if scheduling_type:
        # Our generator produced "SELF" and "REQUEST" types.
        # But the API might receive "SELF-TYPE".
        target_type = scheduling_type.replace("-TYPE", "")
        filtered = [j for j in ALL_DATA if j.get("type") == target_type]

    total = len(filtered)
    end = offset + limit
    page = filtered[offset:end]
    next_offset = end if end < total else None

    return {
        "status": "success",
        "result": page,
        "pagination": {
            "limit": limit,
            "offset": offset,
            "next_offset": next_offset,
            "total": total,
        },
    }


@app.get("/api/job/{job_id}")
def get_job_legacy(job_id: str):
    """Legacy endpoint for Job Manager compatibility."""
    for item in ALL_DATA:
        if item["job_id"] == job_id:
            return item
    return None

@app.get("/api/job/job-run-history/")
def get_job_run_history_legacy(
    job_id: str = Query(...),
    limit: int = 100,
    offset: int = 0
):
    """Legacy endpoint called by Lineage Manager adapter."""
    return get_job_run_history(job_id)

@app.get("/job/{job_id}/run-history")
def get_job_run_history(job_id: str):
    """Return 30 synthetic run-history items for the given job."""
    base_end = datetime(2025, 12, 3, 1, 0, tzinfo=timezone.utc)
    runs = []
    for idx in range(30):
        end_at = base_end - timedelta(days=idx)
        start_at = end_at + timedelta(hours=-72 + (idx % 6))  # some variety
        # Alternate states
        state = ["RUNNING", "SUCCESS", "FAILED", "SUCCESS", "SUCCESS", "FAILED"][idx % 6]
        finish_time = None if state == "RUNNING" else start_at + timedelta(minutes=30 + idx)
        runs.append(
            {
                "job_id": job_id,
                "data_interval_end": end_at.strftime("%Y-%m-%dT%H:%M:%S"),
                "dag_run_id": f"scheduled__{(end_at - timedelta(days=1)).isoformat()}",
                "state": state,
                "start_time": start_at.strftime("%Y-%m-%dT%H:%M:%S"),
                "finish_time": finish_time.strftime("%Y-%m-%dT%H:%M:%S") if finish_time else None,
                "delay_criteria": [],
                "notified": False if state != "RUNNING" else None,
            }
        )
    return runs


@app.post("/api/v1/jobs/scheduling-lineage/by_ids")
def get_scheduling_lineage_by_ids(payload: JobSelectorRequest):
    """Return specific jobs by ID from the static dataset."""
    requested_ids = {j.job_id for j in payload.jobs}
    
    results = [j for j in ALL_DATA if j["job_id"] in requested_ids]

    return {
        "status": "success",
        "result": results,
        "pagination": {"limit": len(results), "offset": 0, "next_offset": None, "total": len(results)},
    }
