replicaCount: 1
fullnameOverride: "admin-mfe-lineage"

image:
  repository: asia-northeast3-docker.pkg.dev/sec-bdp-user-dev/self-scheduling-dev1/admin-mfe-lineage
  pullPolicy: Always
  tag: "latest"

serviceAccount:
  create: false
  name: "self-scheduling"

namespace: "self-scheduling-dev1"

service:
  type: NodePort
  port: 5101
  targetPort: 80
  annotations:
    cloud.google.com/backend-config: '{"default": "self-scheduling-backend"}'
    cloud.google.com/neg: '{"ingress": true}'

livenessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  NODE_ENV: "production"
  BASE_URL: "/admin-console/mfe-lineage"
  API_BASE_URL: "/admin-console"
  CATALOG_MFE_URL: "https://dev1-self-scheduling.di.atlas.samsung.com/admin-console/mfe-catalog/remoteEntry.js"
