{{- range $app := list "app" "mfeLineage" "mfeCatalog" }}
{{- $config := index $.Values $app }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $config.name }}
  labels:
    app: {{ $config.name }}
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    release: {{ $.Release.Name }}
  {{- if $.Values.backendConfig.enabled }}
  annotations:
    cloud.google.com/backend-config: '{"default": "{{ $.Values.backendConfig.name }}"}'
    cloud.google.com/neg: '{"ingress": true}'
  {{- end }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ $config.name }}
{{- end }}
